import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './navbar';
import Sidebar from './sidebar';
import Main from './main';
import Footer from './footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <div className='body flex flex-row'>
          <Sidebar />
          <Main />
        </div>
        <Footer />
        {children}
      </body>
    </html>
  );
}
